# Generated by Django 3.1.4 on 2024-03-01 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingOffer',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='/placeholder.jpg', null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('location', models.CharField(max_length=255)),
                ('number_of_rooms', models.PositiveSmallIntegerField()),
                ('is_furnished', models.BooleanField()),
                ('is_pet_friendly', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HousingRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('housing_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nestquest.housingoffer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nestquest.housingrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HousingOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('housing_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestquest.housingoffer')),
            ],
        ),
    ]
