# Generated by Django 3.1.4 on 2024-02-14 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nestquest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desired_location', models.CharField(max_length=100)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('min_bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('is_furnished_desired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
