# Generated by Django 3.1.4 on 2024-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestquest', '0003_housingoffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingoffer',
            name='is_furnished',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No')]),
        ),
        migrations.AlterField(
            model_name='housingoffer',
            name='is_pet_friendly',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No')]),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='is_furnished_desired',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No')]),
        ),
    ]
