# Generated by Django 3.1.4 on 2024-02-18 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nestquest', '0005_auto_20240217_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingrequest',
            name='desired_location',
        ),
        migrations.RemoveField(
            model_name='housingrequest',
            name='is_furnished_desired',
        ),
        migrations.RemoveField(
            model_name='housingrequest',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='housingrequest',
            name='min_bathrooms',
        ),
        migrations.RemoveField(
            model_name='housingrequest',
            name='min_bedrooms',
        ),
        migrations.RemoveField(
            model_name='housingrequest',
            name='move_in_date',
        ),
        migrations.RemoveField(
            model_name='housingrequest',
            name='title',
        ),
        migrations.RemoveField(
            model_name='housingrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='housingrequest',
            name='housing_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nestquest.housingoffer'),
        ),
        migrations.AddField(
            model_name='housingrequest',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='nestquest.housingrequest'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
