# Generated by Django 3.1.4 on 2024-02-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestquest', '0013_auto_20240218_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingrequest',
            name='housing_offer',
        ),
        migrations.RemoveField(
            model_name='message',
            name='request',
        ),
    ]
