# Generated by Django 3.1.4 on 2024-02-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestquest', '0019_auto_20240218_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingoffer',
            name='is_furnished',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='housingoffer',
            name='is_pet_friendly',
            field=models.BooleanField(),
        ),
    ]
