# Generated by Django 3.1.4 on 2024-02-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestquest', '0020_auto_20240219_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='housing_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nestquest.housingoffer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nestquest.housingrequest'),
        ),
    ]
